<a href="/users/new">Новый пользователь</a>

<?php if (!empty($flashMessages)) : ?>
  <?php foreach ($flashMessages as $message) : ?>
    <div style="border: 1px solid green;"><?= $message ?></div>
  <?php endforeach; ?>
<?php endif; ?>

<table>
<?php foreach ($users as $user): ?>
  <tr>
    <td><?= htmlspecialchars($user['id']) ?></td>
    <td><?= htmlspecialchars($user['nickname']) ?></td>
    <td><?= htmlspecialchars($user['email']) ?></td>
  </tr>
<?php endforeach ?>
</table>