<?php if (count($flash) > 0): ?>
  <ul>
  <?php foreach ($flash as $messages): ?>
      <?php foreach ($messages as $message): ?>
          <li><?= $message ?></li>
      <?php endforeach ?>
  <?php endforeach ?>
  </ul>
<?php endif ?>

<a href="/posts/new">Новый пост</a>

<!-- BEGIN (write your solution here) -->
<?php foreach ($posts as $post) : ?>
<form action="/posts/<?= $post['id'] ?>" method="post" >
  <input type="hidden" name="_METHOD" value="DELETE">
  <?= htmlspecialchars($post['name']) ?> <input type="submit" value="Delete">
</form>
<?php endforeach ?>

<!-- END -->
