<a href="/posts">Посты</a>

<!-- BEGIN (write your solution here) -->
<form action="/posts" method="post">
    <div>
        <label>
            Название *
            <input type="text" name="post[name]" value="<?= htmlspecialchars($post['name'] ?? ''); ?>">
        </label>
        <?php if (isset($errors['name'])) : ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Содержимое *
            <!-- <input type="text" name="post[body]" value="<?= htmlspecialchars($post['body'] ?? ''); ?>"> -->
            <textarea type="text" rows="20" cols="80" name="post[body]">
                <?= htmlspecialchars($post['body'] ?? ''); ?>
            </textarea>
        </label>
        <?php if (isset($errors['body'])) : ?>
            <div><?= $errors['body'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Создать">
</form>
<!-- END -->